spanish_corpus_sentences = [
    "Mi hermano come manzanas.",
    "Ella vive en Madrid.",
    "El gato duerme en la silla.",
    "Nosotros leemos un libro interesante.",
    "¿Dónde está el baño?",
    "Hoy hace mucho calor.",
    "Juan y María van al mercado.",
    "El perro corre rápido.",
    "Tengo dos hermanos.",
    "Ella trabaja en una oficina grande.",
    "La profesora explica la lección.",
    "Las flores son bonitas.",
    "Mañana viajaré a Barcelona.",
    "No me gusta el café.",
    "¿Puedes ayudarme, por favor?",
    "El niño juega con su pelota.",
    "La película empieza a las ocho.",
    "Siempre estudio antes del examen.",
    "Esta casa tiene tres habitaciones.",
    "El sol brilla en el cielo.",
    "Ayer fuimos al parque.",
    "Ellos compraron pan y leche.",
    "Mi padre cocina paella los domingos.",
    "El libro está sobre la mesa.",
    "Quiero aprender español.",
    "Tu amiga es muy simpática.",
    "Voy a la tienda.",
    "Ella canta una canción bonita.",
    "Mis hijos van a la escuela.",
    "Los estudiantes escriben en sus cuadernos.",
    "Se necesita agua para vivir.",
    "La ciudad tiene muchos museos.",
    "El tren llega a las diez.",
    "Hace frío en invierno.",
    "Puedo leer y escribir en español.",
    "Tú tienes una bicicleta nueva.",
    "El equipo juega bien.",
    "Este problema es difícil.",
    "La comida está deliciosa.",
    "Me gusta caminar por la playa."
]

spanish_corpus_translations = [
    "My brother eats apples.",
    "She lives in Madrid.",
    "The cat sleeps on the chair.",
    "We read an interesting book.",
    "Where is the bathroom?",
    "Today it is very hot.",
    "Juan and María go to the market.",
    "The dog runs fast.",
    "I have two brothers.",
    "She works in a large office.",
    "The teacher explains the lesson.",
    "The flowers are beautiful.",
    "Tomorrow I will travel to Barcelona.",
    "I do not like coffee.",
    "Can you help me, please?",
    "The child plays with his ball.",
    "The movie starts at eight.",
    "I always study before the exam.",
    "This house has three rooms.",
    "The sun shines in the sky.",
    "Yesterday we went to the park.",
    "They bought bread and milk.",
    "My father cooks paella on Sundays.",
    "The book is on the table.",
    "I want to learn Spanish.",
    "Your friend is very nice.",
    "I am going to the store.",
    "She sings a beautiful song.",
    "My children go to school.",
    "The students write in their notebooks.",
    "Water is needed to live.",
    "The city has many museums.",
    "The train arrives at ten.",
    "It is cold in winter.",
    "I can read and write in Spanish.",
    "You have a new bicycle.",
    "The team plays well.",
    "This problem is difficult.",
    "The food is delicious.",
    "I like walking on the beach."
]

spanish_tagged_sentences = [
    [("Mi", "DET"), ("hermano", "NOUN"), ("come", "VERB"), ("manzanas", "NOUN"), (".", "PUNCT")],
    [("Ella", "PRON"), ("vive", "VERB"), ("en", "ADP"), ("Madrid", "PROPN"), (".", "PUNCT")],
    [("El", "DET"), ("gato", "NOUN"), ("duerme", "VERB"), ("en", "ADP"), ("la", "DET"), ("silla", "NOUN"), (".", "PUNCT")],
    [("Nosotros", "PRON"), ("leemos", "VERB"), ("un", "DET"), ("libro", "NOUN"), ("interesante", "ADJ"), (".", "PUNCT")],
    [("¿", "PUNCT"), ("Dónde", "ADV"), ("está", "AUX"), ("el", "DET"), ("baño", "NOUN"), ("?", "PUNCT")],
    [("Hoy", "NOUN"), ("hace", "VERB"), ("mucho", "ADV"), ("calor", "NOUN"), (".", "PUNCT")],
    [("Juan", "PROPN"), ("y", "CONJ"), ("María", "PROPN"), ("van", "VERB"), ("al", "ADP"), ("mercado", "NOUN"), (".", "PUNCT")],
    [("El", "DET"), ("perro", "NOUN"), ("corre", "VERB"), ("rápido", "ADV"), (".", "PUNCT")],
    [("Tengo", "VERB"), ("dos", "NUM"), ("hermanos", "NOUN"), (".", "PUNCT")],
    [("Ella", "PRON"), ("trabaja", "VERB"), ("en", "ADP"), ("una", "DET"), ("oficina", "NOUN"), ("grande", "ADJ"), (".", "PUNCT")],
    [("La", "DET"), ("profesora", "NOUN"), ("explica", "VERB"), ("la", "DET"), ("lección", "NOUN"), (".", "PUNCT")],
    [("Las", "DET"), ("flores", "NOUN"), ("son", "AUX"), ("bonitas", "ADJ"), (".", "PUNCT")],
    [("Mañana", "NOUN"), ("viajaré", "VERB"), ("a", "ADP"), ("Barcelona", "PROPN"), (".", "PUNCT")],
    [("No", "PART"), ("me", "PRON"), ("gusta", "VERB"), ("el", "DET"), ("café", "NOUN"), (".", "PUNCT")],
    [("¿", "PUNCT"), ("Puedes", "AUX"), ("ayudarme", "VERB"), (",", "PUNCT"), ("por", "ADP"), ("favor", "NOUN"), ("?", "PUNCT")],
    [("El", "DET"), ("niño", "NOUN"), ("juega", "VERB"), ("con", "ADP"), ("su", "DET"), ("pelota", "NOUN"), (".", "PUNCT")],
    [("La", "DET"), ("película", "NOUN"), ("empieza", "VERB"), ("a", "ADP"), ("las", "DET"), ("ocho", "NUM"), (".", "PUNCT")],
    [("Siempre", "ADV"), ("estudio", "VERB"), ("antes", "ADP"), ("del", "ADP"), ("examen", "NOUN"), (".", "PUNCT")],
    [("Esta", "DET"), ("casa", "NOUN"), ("tiene", "VERB"), ("tres", "NUM"), ("habitaciones", "NOUN"), (".", "PUNCT")],
    [("El", "DET"), ("sol", "NOUN"), ("brilla", "VERB"), ("en", "ADP"), ("el", "DET"), ("cielo", "NOUN"), (".", "PUNCT")],
    [("Ayer", "NOUN"), ("fuimos", "VERB"), ("al", "ADP"), ("parque", "NOUN"), (".", "PUNCT")],
    [("Ellos", "PRON"), ("compraron", "VERB"), ("pan", "NOUN"), ("y", "CONJ"), ("leche", "NOUN"), (".", "PUNCT")],
    [("Mi", "DET"), ("padre", "NOUN"), ("cocina", "VERB"), ("paella", "NOUN"), ("los", "DET"), ("domingos", "NOUN"), (".", "PUNCT")],
    [("El", "DET"), ("libro", "NOUN"), ("está", "AUX"), ("sobre", "ADP"), ("la", "DET"), ("mesa", "NOUN"), (".", "PUNCT")],
    [("Quiero", "VERB"), ("aprender", "VERB"), ("español", "NOUN"), (".", "PUNCT")],
    [("Tu", "DET"), ("amiga", "NOUN"), ("es", "AUX"), ("muy", "ADV"), ("simpática", "ADJ"), (".", "PUNCT")],
    [("Voy", "VERB"), ("a", "ADP"), ("la", "DET"), ("tienda", "NOUN"), (".", "PUNCT")],
    [("Ella", "PRON"), ("canta", "VERB"), ("una", "DET"), ("canción", "NOUN"), ("bonita", "ADJ"), (".", "PUNCT")],
    [("Mis", "DET"), ("hijos", "NOUN"), ("van", "VERB"), ("a", "ADP"), ("la", "DET"), ("escuela", "NOUN"), (".", "PUNCT")],
    [("Los", "DET"), ("estudiantes", "NOUN"), ("escriben", "VERB"), ("en", "ADP"), ("sus", "DET"), ("cuadernos", "NOUN"), (".", "PUNCT")],
    [("Se", "PRON"), ("necesita", "VERB"), ("agua", "NOUN"), ("para", "ADP"), ("vivir", "VERB"), (".", "PUNCT")],
    [("La", "DET"), ("ciudad", "NOUN"), ("tiene", "VERB"), ("muchos", "ADJ"), ("museos", "NOUN"), (".", "PUNCT")],
    [("El", "DET"), ("tren", "NOUN"), ("llega", "VERB"), ("a", "ADP"), ("las", "DET"), ("diez", "NUM"), (".", "PUNCT")],
    [("Hace", "VERB"), ("frío", "ADJ"), ("en", "ADP"), ("invierno", "NOUN"), (".", "PUNCT")],
    [("Puedo", "VERB"), ("leer", "VERB"), ("y", "CONJ"), ("escribir", "VERB"), ("en", "ADP"), ("español", "NOUN"), (".", "PUNCT")],
    [("Tú", "PRON"), ("tienes", "VERB"), ("una", "DET"), ("bicicleta", "NOUN"), ("nueva", "ADJ"), (".", "PUNCT")],
    [("El", "DET"), ("equipo", "NOUN"), ("juega", "VERB"), ("bien", "ADV"), (".", "PUNCT")],
    [("Este", "DET"), ("problema", "NOUN"), ("es", "AUX"), ("difícil", "ADJ"), (".", "PUNCT")],
    [("La", "DET"), ("comida", "NOUN"), ("está", "AUX"), ("deliciosa", "ADJ"), (".", "PUNCT")],
    [("Me", "PRON"), ("gusta", "VERB"), ("caminar", "VERB"), ("por", "ADP"), ("la", "DET"), ("playa", "NOUN"), (".", "PUNCT")]
]
